repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python3 -m unittest discover
        language: python
        types: [python]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
